### ISSUE TITLE
Improvement - Component Button data table

### ISSUE THREAD

**Issue by niklasros** [scania-digital-design-system/sdds-website#150]
**Describe current situation**  
_The data table for Types has the wrong width_
_The text has the wrong color_

**Describe the improvement**  
_Change the width to 928 px (12 cols on xxlarge)._
_Change the text colour to $grey-700_

**Screenshots**  
_Implementation_
<img width="691" alt="component-data-table-button-implementation" src="https://user-images.githubusercontent.com/59045455/102226978-5340f480-3ee9-11eb-8445-2e534270a2f1.png">

_Figma_
<img width="995" alt="component-data-table-button-figma" src="https://user-images.githubusercontent.com/59045455/102227003-59cf6c00-3ee9-11eb-9635-da21985e769c.png">

**Comment by mmexvr** [comment]
Right now, tables are based on the one column solution which is xxlg-9.

Improvement to add is the option to, maybe in the cms ,the possibilty to choose how big the content should be from the cms

**Comment by niklasros** [comment]
> Right now, tables are based on the one column solution which is xxlg-9.
> 
> Improvement to add is the option to, maybe in the cms ,the possibilty to choose how big the content should be from the cms

I think that would be great to look into in Q1!
