### ISSUE TITLE
Improvement - Text field placeholder text

### ISSUE THREAD

**Issue by niklasros** [scania-digital-design-system/sdds-website#162]
**Describe current situation**  
_The Placeholder text in the text field jumps up 1px when focused._

**Describe the improvement**  
_Make sure that the Placeholder text is in the same position for default as focused._

**If applicable, please provide steps to reproduce**
_Steps to reproduce the behavior:_  
1. Go to 'https://deploy-preview-156--digitaldesign.netlify.app/foundation/pictograms/pictograms'
2. Click on 'text field'
3. See error (Placeholder texts positiion moves 1px in Y-axis)

**Screenshots**  
_If applicable, add screenshots to help explain your ideas._

**Additional context**  
_https://deploy-preview-156--digitaldesign.netlify.app/foundation/pictograms/pictograms_

**Comment by mmexvr** [comment]
Safari and firefox problem

**Comment by mmexvr** [comment]
Should probably be fixed when textfield component is being worked on
