### ISSUE TITLE
Improvement - Anchor links

### ISSUE THREAD

**Issue by niklasros** [scania-digital-design-system/sdds-website#166]
**Describe current situation**  
_When scrolling on a detail page, the sticky anchor link component doesn't tell the user which section the user is at._

**Describe the improvement**  
_The anchor link component should show the user where they are on the page._

**If applicable, please provide steps to reproduce**
_Steps to reproduce the behavior:_  
1. Go to any page with anchor links
2. Click on any link in the anchor links component
3. See error

And:
4. Scroll on the detail page
5. See error

**Screenshot**  
![anchor-links](https://user-images.githubusercontent.com/59045455/102319364-0c9bda80-3f7b-11eb-88fe-e666c2df7bae.png)

**Additional context**  
_https://digitaldesign.netlify.app/foundation/spacing_

**Comment by mmexvr** [comment]
Active state logic needs to be added
