### ISSUE TITLE
Improvement - Github page name

### ISSUE THREAD

**Issue by alexlioliopoulos** [scania-digital-design-system/sdds-website#191]
Really not sure if this a problem, but I saw that we are using the term "corporate ui" still in github. Could we change that?

**Comment by helloimela** [comment]
If this repository is the one that you mention, we will move it later. We will do it one by one.
Right now we started with components & packages, and we'll not use everything under corporate-ui anymore.
This is our new official organisation https://github.com/scania-digital-design-system/

**Comment by alexlioliopoulos** [comment]
Yes, perfect. I know that you probably had a plan for this, but wasn't sure 🥇

**Comment by mmexvr** [comment]
@alexlioliopoulos, I will closing this issue

- Have moved all repositories(code) to a new organiazation called scania digital design system
- Changed name(Repository name) to sdds-website

**Comment by mmexvr** [comment]
Solved
